language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -y lcov g++-4.8 gcc-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 90
  - gem install coveralls-lcov
  - git submodule update --init --recursive
  - mkdir build
  - cd build
script:
  - cmake ..
  - make
after_success:
  - git clone https://github.com/linux-test-project/lcov.git
  - lcov/bin/lcov --capture --directory CMakeFiles --output-file coverage --rc lcov_branch_coverage=1
  - lcov/bin/lcov --remove coverage '/usr/include/*' 'ext/*' 'test/*' -o coverage.filtered --rc lcov_branch_coverage=1
  - lcov/bin/lcov -l coverage.filtered --rc lcov_branch_coverage=1
  - coveralls-lcov coverage.filtered
