#include <string>
#include <map>
#include <iostream>
#include "card_500.h"

static Card::colour_t const suit_colour[] = {
   [Card::none] = Card::neither,
   [Card::hearts] = Card::red,
   [Card::diamonds] = Card::red,
   [Card::clubs] = Card::black,
   [Card::spades] = Card::black
};

Card::Card(suit_t suit, number_t number)
   : _suit(suit), _number(number), _colour(suit_colour[suit])
{
}

bool operator== (Card const &c1, Card const &c2)
{
   if (c1.suit() != c2.suit()) return false;
   if (c1.number() != c2.number()) return false;
   return true;
}

bool operator!= (Card const &c1, Card const &c2)
{
   return !(c1 == c2);
}

Card::suit_t Card::suit() const
{
   return _suit;
}

Card::number_t Card::number() const
{
   return _number;
}

Card::colour_t Card::colour() const
{
   return _colour;
}

std::string Card::print() const
{
   if (_number == joker) return "Jo";
   return print_short_number() + print_short_suit();
}

std::string Card::print_full() const
{
   static std::map <Card::suit_t, std::string> const print_full_suit = {
      {Card::hearts, "Hearts"},
      {Card::diamonds, "Diamonds"},
      {Card::spades, "Spades"},
      {Card::clubs, "Clubs"}
   };
   static std::map <Card::number_t, std::string> const print_full_number = {
      {Card::ace, "Ace"},
      {Card::two, "2"},
      {Card::three, "3"},
      {Card::four, "4"},
      {Card::five, "5"},
      {Card::six, "6"},
      {Card::seven, "7"},
      {Card::eight, "8"},
      {Card::nine, "9"},
      {Card::ten, "10"},
      {Card::jack, "Jack"},
      {Card::queen, "Queen"},
      {Card::king, "King"}
   };

   if (_number == joker) return "The Joker";
   return find_with_exception(print_full_number, _number) + " of " + find_with_exception(print_full_suit, _suit);
}

std::string Card::print_short_suit() const
{
   static std::map <Card::suit_t, std::string> const print_short_suit = {
      {Card::hearts, "♥"},
      {Card::diamonds, "♦"},
      {Card::spades, "♠"},
      {Card::clubs, "♣"}
   };
   return find_with_exception(print_short_suit, _suit);
}

std::string Card::print_short_number() const
{
   static std::map <Card::number_t, std::string> const print_short_number = {
      {Card::ace, "A"},
      {Card::two, "2"},
      {Card::three, "3"},
      {Card::four, "4"},
      {Card::five, "5"},
      {Card::six, "6"},
      {Card::seven, "7"},
      {Card::eight, "8"},
      {Card::nine, "9"},
      {Card::ten, "10"},
      {Card::jack, "J"},
      {Card::queen, "Q"},
      {Card::king, "K"}
   };
   return find_with_exception(print_short_number, _number);
}

Card_500::Card_500(suit_t s, number_t n)
   : Card(s, n)
{
}

static Card::colour_t const trumps_colour[] = {
   [Game_500::hearts] = Card::red,
   [Game_500::diamonds] = Card::red,
   [Game_500::clubs] = Card::black,
   [Game_500::spades] = Card::black,
   [Game_500::no_trumps] = Card::neither,
   [Game_500::misere] = Card::neither
};

static Card::suit_t const play_suit[6][5][14] = {
   [Game_500::hearts] = {
      [Card::none] = {
         [Card::ace] = Card::none,
         [Card::two] = Card::none,
         [Card::three] = Card::none,
         [Card::four] = Card::none,
         [Card::five] = Card::none,
         [Card::six] = Card::none,
         [Card::seven] = Card::none,
         [Card::eight] = Card::none,
         [Card::nine] = Card::none,
         [Card::ten] = Card::none,
         [Card::jack] = Card::none,
         [Card::queen] = Card::none,
         [Card::king] = Card::none,
         [Card::joker] = Card::hearts
      },
      [Card::hearts] = {
         [Card::ace] = Card::hearts,
         [Card::two] = Card::hearts,
         [Card::three] = Card::hearts,
         [Card::four] = Card::hearts,
         [Card::five] = Card::hearts,
         [Card::six] = Card::hearts,
         [Card::seven] = Card::hearts,
         [Card::eight] = Card::hearts,
         [Card::nine] = Card::hearts,
         [Card::ten] = Card::hearts,
         [Card::jack] = Card::hearts,
         [Card::queen] = Card::hearts,
         [Card::king] = Card::hearts,
         [Card::joker] = Card::hearts
      },
      [Card::diamonds] = {
         [Card::ace] = Card::diamonds,
         [Card::two] = Card::diamonds,
         [Card::three] = Card::diamonds,
         [Card::four] = Card::diamonds,
         [Card::five] = Card::diamonds,
         [Card::six] = Card::diamonds,
         [Card::seven] = Card::diamonds,
         [Card::eight] = Card::diamonds,
         [Card::nine] = Card::diamonds,
         [Card::ten] = Card::diamonds,
         [Card::jack] = Card::hearts,
         [Card::queen] = Card::diamonds,
         [Card::king] = Card::diamonds,
         [Card::joker] = Card::hearts
      },
      [Card::clubs] = {
         [Card::ace] = Card::clubs,
         [Card::two] = Card::clubs,
         [Card::three] = Card::clubs,
         [Card::four] = Card::clubs,
         [Card::five] = Card::clubs,
         [Card::six] = Card::clubs,
         [Card::seven] = Card::clubs,
         [Card::eight] = Card::clubs,
         [Card::nine] = Card::clubs,
         [Card::ten] = Card::clubs,
         [Card::jack] = Card::clubs,
         [Card::queen] = Card::clubs,
         [Card::king] = Card::clubs,
         [Card::joker] = Card::hearts
      },
      [Card::spades] = {
         [Card::ace] = Card::spades,
         [Card::two] = Card::spades,
         [Card::three] = Card::spades,
         [Card::four] = Card::spades,
         [Card::five] = Card::spades,
         [Card::six] = Card::spades,
         [Card::seven] = Card::spades,
         [Card::eight] = Card::spades,
         [Card::nine] = Card::spades,
         [Card::ten] = Card::spades,
         [Card::jack] = Card::spades,
         [Card::queen] = Card::spades,
         [Card::king] = Card::spades,
         [Card::joker] = Card::hearts
      }
   },
   [Game_500::diamonds] = {
      [Card::none] = {
         [Card::ace] = Card::none,
         [Card::two] = Card::none,
         [Card::three] = Card::none,
         [Card::four] = Card::none,
         [Card::five] = Card::none,
         [Card::six] = Card::none,
         [Card::seven] = Card::none,
         [Card::eight] = Card::none,
         [Card::nine] = Card::none,
         [Card::ten] = Card::none,
         [Card::jack] = Card::none,
         [Card::queen] = Card::none,
         [Card::king] = Card::none,
         [Card::joker] = Card::diamonds
      },
      [Card::hearts] = {
         [Card::ace] = Card::hearts,
         [Card::two] = Card::hearts,
         [Card::three] = Card::hearts,
         [Card::four] = Card::hearts,
         [Card::five] = Card::hearts,
         [Card::six] = Card::hearts,
         [Card::seven] = Card::hearts,
         [Card::eight] = Card::hearts,
         [Card::nine] = Card::hearts,
         [Card::ten] = Card::hearts,
         [Card::jack] = Card::diamonds,
         [Card::queen] = Card::hearts,
         [Card::king] = Card::hearts,
         [Card::joker] = Card::diamonds
      },
      [Card::diamonds] = {
         [Card::ace] = Card::diamonds,
         [Card::two] = Card::diamonds,
         [Card::three] = Card::diamonds,
         [Card::four] = Card::diamonds,
         [Card::five] = Card::diamonds,
         [Card::six] = Card::diamonds,
         [Card::seven] = Card::diamonds,
         [Card::eight] = Card::diamonds,
         [Card::nine] = Card::diamonds,
         [Card::ten] = Card::diamonds,
         [Card::jack] = Card::diamonds,
         [Card::queen] = Card::diamonds,
         [Card::king] = Card::diamonds,
         [Card::joker] = Card::diamonds
      },
      [Card::clubs] = {
         [Card::ace] = Card::clubs,
         [Card::two] = Card::clubs,
         [Card::three] = Card::clubs,
         [Card::four] = Card::clubs,
         [Card::five] = Card::clubs,
         [Card::six] = Card::clubs,
         [Card::seven] = Card::clubs,
         [Card::eight] = Card::clubs,
         [Card::nine] = Card::clubs,
         [Card::ten] = Card::clubs,
         [Card::jack] = Card::clubs,
         [Card::queen] = Card::clubs,
         [Card::king] = Card::clubs,
         [Card::joker] = Card::diamonds
      },
      [Card::spades] = {
         [Card::ace] = Card::spades,
         [Card::two] = Card::spades,
         [Card::three] = Card::spades,
         [Card::four] = Card::spades,
         [Card::five] = Card::spades,
         [Card::six] = Card::spades,
         [Card::seven] = Card::spades,
         [Card::eight] = Card::spades,
         [Card::nine] = Card::spades,
         [Card::ten] = Card::spades,
         [Card::jack] = Card::spades,
         [Card::queen] = Card::spades,
         [Card::king] = Card::spades,
         [Card::joker] = Card::diamonds
      }
   },
   [Game_500::clubs] = {
      [Card::none] = {
         [Card::ace] = Card::none,
         [Card::two] = Card::none,
         [Card::three] = Card::none,
         [Card::four] = Card::none,
         [Card::five] = Card::none,
         [Card::six] = Card::none,
         [Card::seven] = Card::none,
         [Card::eight] = Card::none,
         [Card::nine] = Card::none,
         [Card::ten] = Card::none,
         [Card::jack] = Card::none,
         [Card::queen] = Card::none,
         [Card::king] = Card::none,
         [Card::joker] = Card::clubs
      },
      [Card::hearts] = {
         [Card::ace] = Card::hearts,
         [Card::two] = Card::hearts,
         [Card::three] = Card::hearts,
         [Card::four] = Card::hearts,
         [Card::five] = Card::hearts,
         [Card::six] = Card::hearts,
         [Card::seven] = Card::hearts,
         [Card::eight] = Card::hearts,
         [Card::nine] = Card::hearts,
         [Card::ten] = Card::hearts,
         [Card::jack] = Card::hearts,
         [Card::queen] = Card::hearts,
         [Card::king] = Card::hearts,
         [Card::joker] = Card::clubs
      },
      [Card::diamonds] = {
         [Card::ace] = Card::diamonds,
         [Card::two] = Card::diamonds,
         [Card::three] = Card::diamonds,
         [Card::four] = Card::diamonds,
         [Card::five] = Card::diamonds,
         [Card::six] = Card::diamonds,
         [Card::seven] = Card::diamonds,
         [Card::eight] = Card::diamonds,
         [Card::nine] = Card::diamonds,
         [Card::ten] = Card::diamonds,
         [Card::jack] = Card::diamonds,
         [Card::queen] = Card::diamonds,
         [Card::king] = Card::diamonds,
         [Card::joker] = Card::clubs
      },
      [Card::clubs] = {
         [Card::ace] = Card::clubs,
         [Card::two] = Card::clubs,
         [Card::three] = Card::clubs,
         [Card::four] = Card::clubs,
         [Card::five] = Card::clubs,
         [Card::six] = Card::clubs,
         [Card::seven] = Card::clubs,
         [Card::eight] = Card::clubs,
         [Card::nine] = Card::clubs,
         [Card::ten] = Card::clubs,
         [Card::jack] = Card::clubs,
         [Card::queen] = Card::clubs,
         [Card::king] = Card::clubs,
         [Card::joker] = Card::clubs
      },
      [Card::spades] = {
         [Card::ace] = Card::spades,
         [Card::two] = Card::spades,
         [Card::three] = Card::spades,
         [Card::four] = Card::spades,
         [Card::five] = Card::spades,
         [Card::six] = Card::spades,
         [Card::seven] = Card::spades,
         [Card::eight] = Card::spades,
         [Card::nine] = Card::spades,
         [Card::ten] = Card::spades,
         [Card::jack] = Card::clubs,
         [Card::queen] = Card::spades,
         [Card::king] = Card::spades,
         [Card::joker] = Card::clubs
      }
   },
   [Game_500::spades] = {
      [Card::none] = {
         [Card::ace] = Card::none,
         [Card::two] = Card::none,
         [Card::three] = Card::none,
         [Card::four] = Card::none,
         [Card::five] = Card::none,
         [Card::six] = Card::none,
         [Card::seven] = Card::none,
         [Card::eight] = Card::none,
         [Card::nine] = Card::none,
         [Card::ten] = Card::none,
         [Card::jack] = Card::none,
         [Card::queen] = Card::none,
         [Card::king] = Card::none,
         [Card::joker] = Card::spades
      },
      [Card::hearts] = {
         [Card::ace] = Card::hearts,
         [Card::two] = Card::hearts,
         [Card::three] = Card::hearts,
         [Card::four] = Card::hearts,
         [Card::five] = Card::hearts,
         [Card::six] = Card::hearts,
         [Card::seven] = Card::hearts,
         [Card::eight] = Card::hearts,
         [Card::nine] = Card::hearts,
         [Card::ten] = Card::hearts,
         [Card::jack] = Card::hearts,
         [Card::queen] = Card::hearts,
         [Card::king] = Card::hearts,
         [Card::joker] = Card::spades
      },
      [Card::diamonds] = {
         [Card::ace] = Card::diamonds,
         [Card::two] = Card::diamonds,
         [Card::three] = Card::diamonds,
         [Card::four] = Card::diamonds,
         [Card::five] = Card::diamonds,
         [Card::six] = Card::diamonds,
         [Card::seven] = Card::diamonds,
         [Card::eight] = Card::diamonds,
         [Card::nine] = Card::diamonds,
         [Card::ten] = Card::diamonds,
         [Card::jack] = Card::diamonds,
         [Card::queen] = Card::diamonds,
         [Card::king] = Card::diamonds,
         [Card::joker] = Card::spades
      },
      [Card::clubs] = {
         [Card::ace] = Card::clubs,
         [Card::two] = Card::clubs,
         [Card::three] = Card::clubs,
         [Card::four] = Card::clubs,
         [Card::five] = Card::clubs,
         [Card::six] = Card::clubs,
         [Card::seven] = Card::clubs,
         [Card::eight] = Card::clubs,
         [Card::nine] = Card::clubs,
         [Card::ten] = Card::clubs,
         [Card::jack] = Card::spades,
         [Card::queen] = Card::clubs,
         [Card::king] = Card::clubs,
         [Card::joker] = Card::spades
      },
      [Card::spades] = {
         [Card::ace] = Card::spades,
         [Card::two] = Card::spades,
         [Card::three] = Card::spades,
         [Card::four] = Card::spades,
         [Card::five] = Card::spades,
         [Card::six] = Card::spades,
         [Card::seven] = Card::spades,
         [Card::eight] = Card::spades,
         [Card::nine] = Card::spades,
         [Card::ten] = Card::spades,
         [Card::jack] = Card::spades,
         [Card::queen] = Card::spades,
         [Card::king] = Card::spades,
         [Card::joker] = Card::spades
      }
   },
   [Game_500::no_trumps] = {
      [Card::none] = {
         [Card::ace] = Card::none,
         [Card::two] = Card::none,
         [Card::three] = Card::none,
         [Card::four] = Card::none,
         [Card::five] = Card::none,
         [Card::six] = Card::none,
         [Card::seven] = Card::none,
         [Card::eight] = Card::none,
         [Card::nine] = Card::none,
         [Card::ten] = Card::none,
         [Card::jack] = Card::none,
         [Card::queen] = Card::none,
         [Card::king] = Card::none,
         [Card::joker] = Card::none
      },
      [Card::hearts] = {
         [Card::ace] = Card::hearts,
         [Card::two] = Card::hearts,
         [Card::three] = Card::hearts,
         [Card::four] = Card::hearts,
         [Card::five] = Card::hearts,
         [Card::six] = Card::hearts,
         [Card::seven] = Card::hearts,
         [Card::eight] = Card::hearts,
         [Card::nine] = Card::hearts,
         [Card::ten] = Card::hearts,
         [Card::jack] = Card::hearts,
         [Card::queen] = Card::hearts,
         [Card::king] = Card::hearts,
         [Card::joker] = Card::hearts
      },
      [Card::diamonds] = {
         [Card::ace] = Card::diamonds,
         [Card::two] = Card::diamonds,
         [Card::three] = Card::diamonds,
         [Card::four] = Card::diamonds,
         [Card::five] = Card::diamonds,
         [Card::six] = Card::diamonds,
         [Card::seven] = Card::diamonds,
         [Card::eight] = Card::diamonds,
         [Card::nine] = Card::diamonds,
         [Card::ten] = Card::diamonds,
         [Card::jack] = Card::diamonds,
         [Card::queen] = Card::diamonds,
         [Card::king] = Card::diamonds,
         [Card::joker] = Card::diamonds
      },
      [Card::clubs] = {
         [Card::ace] = Card::clubs,
         [Card::two] = Card::clubs,
         [Card::three] = Card::clubs,
         [Card::four] = Card::clubs,
         [Card::five] = Card::clubs,
         [Card::six] = Card::clubs,
         [Card::seven] = Card::clubs,
         [Card::eight] = Card::clubs,
         [Card::nine] = Card::clubs,
         [Card::ten] = Card::clubs,
         [Card::jack] = Card::spades,
         [Card::queen] = Card::clubs,
         [Card::king] = Card::clubs,
         [Card::joker] = Card::clubs
      },
      [Card::spades] = {
         [Card::ace] = Card::spades,
         [Card::two] = Card::spades,
         [Card::three] = Card::spades,
         [Card::four] = Card::spades,
         [Card::five] = Card::spades,
         [Card::six] = Card::spades,
         [Card::seven] = Card::spades,
         [Card::eight] = Card::spades,
         [Card::nine] = Card::spades,
         [Card::ten] = Card::spades,
         [Card::jack] = Card::spades,
         [Card::queen] = Card::spades,
         [Card::king] = Card::spades,
         [Card::joker] = Card::spades
      }
   },
   [Game_500::misere] = {
      [Card::none] = {
         [Card::ace] = Card::none,
         [Card::two] = Card::none,
         [Card::three] = Card::none,
         [Card::four] = Card::none,
         [Card::five] = Card::none,
         [Card::six] = Card::none,
         [Card::seven] = Card::none,
         [Card::eight] = Card::none,
         [Card::nine] = Card::none,
         [Card::ten] = Card::none,
         [Card::jack] = Card::none,
         [Card::queen] = Card::none,
         [Card::king] = Card::none,
         [Card::joker] = Card::none
      },
      [Card::hearts] = {
         [Card::ace] = Card::hearts,
         [Card::two] = Card::hearts,
         [Card::three] = Card::hearts,
         [Card::four] = Card::hearts,
         [Card::five] = Card::hearts,
         [Card::six] = Card::hearts,
         [Card::seven] = Card::hearts,
         [Card::eight] = Card::hearts,
         [Card::nine] = Card::hearts,
         [Card::ten] = Card::hearts,
         [Card::jack] = Card::hearts,
         [Card::queen] = Card::hearts,
         [Card::king] = Card::hearts,
         [Card::joker] = Card::hearts
      },
      [Card::diamonds] = {
         [Card::ace] = Card::diamonds,
         [Card::two] = Card::diamonds,
         [Card::three] = Card::diamonds,
         [Card::four] = Card::diamonds,
         [Card::five] = Card::diamonds,
         [Card::six] = Card::diamonds,
         [Card::seven] = Card::diamonds,
         [Card::eight] = Card::diamonds,
         [Card::nine] = Card::diamonds,
         [Card::ten] = Card::diamonds,
         [Card::jack] = Card::diamonds,
         [Card::queen] = Card::diamonds,
         [Card::king] = Card::diamonds,
         [Card::joker] = Card::diamonds
      },
      [Card::clubs] = {
         [Card::ace] = Card::clubs,
         [Card::two] = Card::clubs,
         [Card::three] = Card::clubs,
         [Card::four] = Card::clubs,
         [Card::five] = Card::clubs,
         [Card::six] = Card::clubs,
         [Card::seven] = Card::clubs,
         [Card::eight] = Card::clubs,
         [Card::nine] = Card::clubs,
         [Card::ten] = Card::clubs,
         [Card::jack] = Card::spades,
         [Card::queen] = Card::clubs,
         [Card::king] = Card::clubs,
         [Card::joker] = Card::clubs
      },
      [Card::spades] = {
         [Card::ace] = Card::spades,
         [Card::two] = Card::spades,
         [Card::three] = Card::spades,
         [Card::four] = Card::spades,
         [Card::five] = Card::spades,
         [Card::six] = Card::spades,
         [Card::seven] = Card::spades,
         [Card::eight] = Card::spades,
         [Card::nine] = Card::spades,
         [Card::ten] = Card::spades,
         [Card::jack] = Card::spades,
         [Card::queen] = Card::spades,
         [Card::king] = Card::spades,
         [Card::joker] = Card::spades
      }
   }
};

Card::suit_t Card_500::suit(Game_500::suit_t trumps) const
{
   return play_suit[trumps][_suit][_number];
}

static unsigned const win_number_table[6][5][5][14] = {
   [Game_500::hearts] = { // hearts as trumps
      [Card::none] = { // led should never return Card::none
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::hearts] = { // hearts led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 80
         },
         [Card::hearts] = { // trumps, led played
            [Card::ace] = 77,
            [Card::two] = 65,
            [Card::three] = 66,
            [Card::four] = 67,
            [Card::five] = 68,
            [Card::six] = 69,
            [Card::seven] = 70,
            [Card::eight] = 71,
            [Card::nine] = 72,
            [Card::ten] = 73,
            [Card::jack] = 79,
            [Card::queen] = 75,
            [Card::king] = 76,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 78,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::diamonds] = { // diamonds led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 60
         },
         [Card::hearts] = { // trumps played
            [Card::ace] = 57,
            [Card::two] = 45,
            [Card::three] = 46,
            [Card::four] = 47,
            [Card::five] = 48,
            [Card::six] = 49,
            [Card::seven] = 50,
            [Card::eight] = 51,
            [Card::nine] = 52,
            [Card::ten] = 53,
            [Card::jack] = 59,
            [Card::queen] = 55,
            [Card::king] = 56,
            [Card::joker] = 0
         },
         [Card::diamonds] = { // led played
            [Card::ace] = 37,
            [Card::two] = 25,
            [Card::three] = 26,
            [Card::four] = 27,
            [Card::five] = 28,
            [Card::six] = 29,
            [Card::seven] = 30,
            [Card::eight] = 31,
            [Card::nine] = 32,
            [Card::ten] = 33,
            [Card::jack] = 58,
            [Card::queen] = 35,
            [Card::king] = 36,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::clubs] = { // clubs led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 60
         },
         [Card::hearts] = { // trumps played
            [Card::ace] = 57,
            [Card::two] = 45,
            [Card::three] = 46,
            [Card::four] = 47,
            [Card::five] = 48,
            [Card::six] = 49,
            [Card::seven] = 50,
            [Card::eight] = 51,
            [Card::nine] = 52,
            [Card::ten] = 53,
            [Card::jack] = 59,
            [Card::queen] = 55,
            [Card::king] = 56,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 58,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = { // led played
            [Card::ace] = 37,
            [Card::two] = 25,
            [Card::three] = 26,
            [Card::four] = 27,
            [Card::five] = 28,
            [Card::six] = 29,
            [Card::seven] = 30,
            [Card::eight] = 31,
            [Card::nine] = 32,
            [Card::ten] = 33,
            [Card::jack] = 34,
            [Card::queen] = 35,
            [Card::king] = 36,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::spades] = { // spades led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 60
         },
         [Card::hearts] = { // trumps played
            [Card::ace] = 57,
            [Card::two] = 45,
            [Card::three] = 46,
            [Card::four] = 47,
            [Card::five] = 48,
            [Card::six] = 49,
            [Card::seven] = 50,
            [Card::eight] = 51,
            [Card::nine] = 52,
            [Card::ten] = 53,
            [Card::jack] = 59,
            [Card::queen] = 55,
            [Card::king] = 56,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 58,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = { // led played
            [Card::ace] = 37,
            [Card::two] = 25,
            [Card::three] = 26,
            [Card::four] = 27,
            [Card::five] = 28,
            [Card::six] = 29,
            [Card::seven] = 30,
            [Card::eight] = 31,
            [Card::nine] = 32,
            [Card::ten] = 33,
            [Card::jack] = 34,
            [Card::queen] = 35,
            [Card::king] = 36,
            [Card::joker] = 0
         }
      }
   },
   [Game_500::diamonds] = { // diamonds as trumps
      [Card::none] = { // led should never return Card::none
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::hearts] = { // hearts led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 60
         },
         [Card::hearts] = { // led played
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 58,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = { // trumps played
            [Card::ace] = 57,
            [Card::two] = 45,
            [Card::three] = 46,
            [Card::four] = 47,
            [Card::five] = 48,
            [Card::six] = 49,
            [Card::seven] = 50,
            [Card::eight] = 51,
            [Card::nine] = 52,
            [Card::ten] = 53,
            [Card::jack] = 59,
            [Card::queen] = 55,
            [Card::king] = 56,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::diamonds] = { // diamonds led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 80
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 78,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = { // led, trumps played
            [Card::ace] = 77,
            [Card::two] = 65,
            [Card::three] = 66,
            [Card::four] = 67,
            [Card::five] = 68,
            [Card::six] = 69,
            [Card::seven] = 70,
            [Card::eight] = 71,
            [Card::nine] = 72,
            [Card::ten] = 73,
            [Card::jack] = 79,
            [Card::queen] = 75,
            [Card::king] = 76,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::clubs] = { // clubs led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 60
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 58,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = { // trumps played
            [Card::ace] = 57,
            [Card::two] = 45,
            [Card::three] = 46,
            [Card::four] = 47,
            [Card::five] = 48,
            [Card::six] = 49,
            [Card::seven] = 50,
            [Card::eight] = 51,
            [Card::nine] = 52,
            [Card::ten] = 53,
            [Card::jack] = 59,
            [Card::queen] = 55,
            [Card::king] = 56,
            [Card::joker] = 0
         },
         [Card::clubs] = { // led played
            [Card::ace] = 37,
            [Card::two] = 25,
            [Card::three] = 26,
            [Card::four] = 27,
            [Card::five] = 28,
            [Card::six] = 29,
            [Card::seven] = 30,
            [Card::eight] = 31,
            [Card::nine] = 32,
            [Card::ten] = 33,
            [Card::jack] = 34,
            [Card::queen] = 35,
            [Card::king] = 36,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::spades] = { // spades led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 60
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 58,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = { // trumps played
            [Card::ace] = 57,
            [Card::two] = 45,
            [Card::three] = 46,
            [Card::four] = 47,
            [Card::five] = 48,
            [Card::six] = 49,
            [Card::seven] = 50,
            [Card::eight] = 51,
            [Card::nine] = 52,
            [Card::ten] = 53,
            [Card::jack] = 59,
            [Card::queen] = 55,
            [Card::king] = 56,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = { // led played
            [Card::ace] = 37,
            [Card::two] = 25,
            [Card::three] = 26,
            [Card::four] = 27,
            [Card::five] = 28,
            [Card::six] = 29,
            [Card::seven] = 30,
            [Card::eight] = 31,
            [Card::nine] = 32,
            [Card::ten] = 33,
            [Card::jack] = 34,
            [Card::queen] = 35,
            [Card::king] = 36,
            [Card::joker] = 0
         }
      }
   },
   [Game_500::clubs] = { // clubs as trumps
      [Card::none] = { // led should never return Card::none
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::hearts] = { // hearts led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 60
         },
         [Card::hearts] = { // led played
            [Card::ace] = 37,
            [Card::two] = 25,
            [Card::three] = 26,
            [Card::four] = 27,
            [Card::five] = 28,
            [Card::six] = 29,
            [Card::seven] = 30,
            [Card::eight] = 31,
            [Card::nine] = 32,
            [Card::ten] = 33,
            [Card::jack] = 34,
            [Card::queen] = 35,
            [Card::king] = 36,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = { // trumps played
            [Card::ace] = 57,
            [Card::two] = 45,
            [Card::three] = 46,
            [Card::four] = 47,
            [Card::five] = 48,
            [Card::six] = 49,
            [Card::seven] = 50,
            [Card::eight] = 51,
            [Card::nine] = 52,
            [Card::ten] = 53,
            [Card::jack] = 59,
            [Card::queen] = 55,
            [Card::king] = 56,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 58,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::diamonds] = { // diamonds led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 60
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = { // led played
            [Card::ace] = 37,
            [Card::two] = 25,
            [Card::three] = 26,
            [Card::four] = 27,
            [Card::five] = 28,
            [Card::six] = 29,
            [Card::seven] = 30,
            [Card::eight] = 31,
            [Card::nine] = 32,
            [Card::ten] = 33,
            [Card::jack] = 34,
            [Card::queen] = 35,
            [Card::king] = 36,
            [Card::joker] = 0
         },
         [Card::clubs] = { // trumps played
            [Card::ace] = 57,
            [Card::two] = 45,
            [Card::three] = 46,
            [Card::four] = 47,
            [Card::five] = 48,
            [Card::six] = 49,
            [Card::seven] = 50,
            [Card::eight] = 51,
            [Card::nine] = 52,
            [Card::ten] = 53,
            [Card::jack] = 59,
            [Card::queen] = 55,
            [Card::king] = 56,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 58,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::clubs] = { // clubs led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 80
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = { // led, trumps played
            [Card::ace] = 77,
            [Card::two] = 65,
            [Card::three] = 66,
            [Card::four] = 67,
            [Card::five] = 68,
            [Card::six] = 69,
            [Card::seven] = 70,
            [Card::eight] = 71,
            [Card::nine] = 72,
            [Card::ten] = 73,
            [Card::jack] = 79,
            [Card::queen] = 75,
            [Card::king] = 76,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 78,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::spades] = { // spades led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 60
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = { // trumps played
            [Card::ace] = 57,
            [Card::two] = 45,
            [Card::three] = 46,
            [Card::four] = 47,
            [Card::five] = 48,
            [Card::six] = 49,
            [Card::seven] = 50,
            [Card::eight] = 51,
            [Card::nine] = 52,
            [Card::ten] = 53,
            [Card::jack] = 59,
            [Card::queen] = 55,
            [Card::king] = 56,
            [Card::joker] = 0
         },
         [Card::spades] = { // led played
            [Card::ace] = 37,
            [Card::two] = 25,
            [Card::three] = 26,
            [Card::four] = 27,
            [Card::five] = 28,
            [Card::six] = 29,
            [Card::seven] = 30,
            [Card::eight] = 31,
            [Card::nine] = 32,
            [Card::ten] = 33,
            [Card::jack] = 58,
            [Card::queen] = 35,
            [Card::king] = 36,
            [Card::joker] = 0
         }
      }
   },
   [Game_500::spades] = { // spades as trumps
      [Card::none] = { // led should never return Card::none
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::hearts] = { // hearts led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 60
         },
         [Card::hearts] = { // led played
            [Card::ace] = 37,
            [Card::two] = 25,
            [Card::three] = 26,
            [Card::four] = 27,
            [Card::five] = 28,
            [Card::six] = 29,
            [Card::seven] = 30,
            [Card::eight] = 31,
            [Card::nine] = 32,
            [Card::ten] = 33,
            [Card::jack] = 34,
            [Card::queen] = 35,
            [Card::king] = 36,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 58,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = { // trumps played
            [Card::ace] = 57,
            [Card::two] = 45,
            [Card::three] = 46,
            [Card::four] = 47,
            [Card::five] = 48,
            [Card::six] = 49,
            [Card::seven] = 50,
            [Card::eight] = 51,
            [Card::nine] = 52,
            [Card::ten] = 53,
            [Card::jack] = 59,
            [Card::queen] = 55,
            [Card::king] = 56,
            [Card::joker] = 0
         }
      },
      [Card::diamonds] = { // diamonds led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 60
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = { // led played
            [Card::ace] = 37,
            [Card::two] = 25,
            [Card::three] = 26,
            [Card::four] = 27,
            [Card::five] = 28,
            [Card::six] = 29,
            [Card::seven] = 30,
            [Card::eight] = 31,
            [Card::nine] = 32,
            [Card::ten] = 33,
            [Card::jack] = 34,
            [Card::queen] = 35,
            [Card::king] = 36,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 58,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = { // trumps played
            [Card::ace] = 57,
            [Card::two] = 45,
            [Card::three] = 46,
            [Card::four] = 47,
            [Card::five] = 48,
            [Card::six] = 49,
            [Card::seven] = 50,
            [Card::eight] = 51,
            [Card::nine] = 52,
            [Card::ten] = 53,
            [Card::jack] = 59,
            [Card::queen] = 55,
            [Card::king] = 56,
            [Card::joker] = 0
         }
      },
      [Card::clubs] = { // clubs led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 60
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = { // led played
            [Card::ace] = 37,
            [Card::two] = 25,
            [Card::three] = 26,
            [Card::four] = 27,
            [Card::five] = 28,
            [Card::six] = 29,
            [Card::seven] = 30,
            [Card::eight] = 31,
            [Card::nine] = 32,
            [Card::ten] = 33,
            [Card::jack] = 58,
            [Card::queen] = 35,
            [Card::king] = 36,
            [Card::joker] = 0
         },
         [Card::spades] = { // trumps played
            [Card::ace] = 57,
            [Card::two] = 45,
            [Card::three] = 46,
            [Card::four] = 47,
            [Card::five] = 48,
            [Card::six] = 49,
            [Card::seven] = 50,
            [Card::eight] = 51,
            [Card::nine] = 52,
            [Card::ten] = 53,
            [Card::jack] = 59,
            [Card::queen] = 55,
            [Card::king] = 56,
            [Card::joker] = 0
         }
      },
      [Card::spades] = { // spades led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 80
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 78,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = { // led, trumps played
            [Card::ace] = 77,
            [Card::two] = 65,
            [Card::three] = 66,
            [Card::four] = 67,
            [Card::five] = 68,
            [Card::six] = 69,
            [Card::seven] = 70,
            [Card::eight] = 71,
            [Card::nine] = 72,
            [Card::ten] = 73,
            [Card::jack] = 79,
            [Card::queen] = 75,
            [Card::king] = 76,
            [Card::joker] = 0
         }
      }
   },
   [Game_500::no_trumps] = { // no_trumps as trumps
      [Card::none] = { // led should never return Card::none
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::hearts] = { // hearts led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 80
         },
         [Card::hearts] = { // led played
            [Card::ace] = 37,
            [Card::two] = 25,
            [Card::three] = 26,
            [Card::four] = 27,
            [Card::five] = 28,
            [Card::six] = 29,
            [Card::seven] = 30,
            [Card::eight] = 31,
            [Card::nine] = 32,
            [Card::ten] = 33,
            [Card::jack] = 34,
            [Card::queen] = 35,
            [Card::king] = 36,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::diamonds] = { // diamonds led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 80
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = { // led played
            [Card::ace] = 37,
            [Card::two] = 25,
            [Card::three] = 26,
            [Card::four] = 27,
            [Card::five] = 28,
            [Card::six] = 29,
            [Card::seven] = 30,
            [Card::eight] = 31,
            [Card::nine] = 32,
            [Card::ten] = 33,
            [Card::jack] = 34,
            [Card::queen] = 35,
            [Card::king] = 36,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::clubs] = { // clubs led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 80
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = { // led played
            [Card::ace] = 37,
            [Card::two] = 25,
            [Card::three] = 26,
            [Card::four] = 27,
            [Card::five] = 28,
            [Card::six] = 29,
            [Card::seven] = 30,
            [Card::eight] = 31,
            [Card::nine] = 32,
            [Card::ten] = 33,
            [Card::jack] = 34,
            [Card::queen] = 35,
            [Card::king] = 36,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::spades] = { // spades led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 80
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = { // led played
            [Card::ace] = 37,
            [Card::two] = 25,
            [Card::three] = 26,
            [Card::four] = 27,
            [Card::five] = 28,
            [Card::six] = 29,
            [Card::seven] = 30,
            [Card::eight] = 31,
            [Card::nine] = 32,
            [Card::ten] = 33,
            [Card::jack] = 34,
            [Card::queen] = 35,
            [Card::king] = 36,
            [Card::joker] = 0
         }
      }
   },
   [Game_500::misere] = { // misere as trumps
      [Card::none] = { // led should never return Card::none
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::hearts] = { // hearts led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 4
         },
         [Card::hearts] = { // led played
            [Card::ace] = 37,
            [Card::two] = 25,
            [Card::three] = 26,
            [Card::four] = 27,
            [Card::five] = 28,
            [Card::six] = 29,
            [Card::seven] = 30,
            [Card::eight] = 31,
            [Card::nine] = 32,
            [Card::ten] = 33,
            [Card::jack] = 34,
            [Card::queen] = 35,
            [Card::king] = 36,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::diamonds] = { // diamonds led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 4
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = { // led played
            [Card::ace] = 37,
            [Card::two] = 25,
            [Card::three] = 26,
            [Card::four] = 27,
            [Card::five] = 28,
            [Card::six] = 29,
            [Card::seven] = 30,
            [Card::eight] = 31,
            [Card::nine] = 32,
            [Card::ten] = 33,
            [Card::jack] = 34,
            [Card::queen] = 35,
            [Card::king] = 36,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::clubs] = { // clubs led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 4
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = { // led played
            [Card::ace] = 37,
            [Card::two] = 25,
            [Card::three] = 26,
            [Card::four] = 27,
            [Card::five] = 28,
            [Card::six] = 29,
            [Card::seven] = 30,
            [Card::eight] = 31,
            [Card::nine] = 32,
            [Card::ten] = 33,
            [Card::jack] = 34,
            [Card::queen] = 35,
            [Card::king] = 36,
            [Card::joker] = 0
         },
         [Card::spades] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         }
      },
      [Card::spades] = { // spades led
         [Card::none] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 4
         },
         [Card::hearts] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::diamonds] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::clubs] = {
            [Card::ace] = 0,
            [Card::two] = 0,
            [Card::three] = 0,
            [Card::four] = 0,
            [Card::five] = 0,
            [Card::six] = 0,
            [Card::seven] = 0,
            [Card::eight] = 0,
            [Card::nine] = 0,
            [Card::ten] = 0,
            [Card::jack] = 0,
            [Card::queen] = 0,
            [Card::king] = 0,
            [Card::joker] = 0
         },
         [Card::spades] = { // led played
            [Card::ace] = 37,
            [Card::two] = 25,
            [Card::three] = 26,
            [Card::four] = 27,
            [Card::five] = 28,
            [Card::six] = 29,
            [Card::seven] = 30,
            [Card::eight] = 31,
            [Card::nine] = 32,
            [Card::ten] = 33,
            [Card::jack] = 34,
            [Card::queen] = 35,
            [Card::king] = 36,
            [Card::joker] = 0
         }
      }
   }
};

unsigned Card_500::win_number(Game_500::suit_t trumps, Card::suit_t led) const
{
   return win_number_table[trumps][led][_suit][_number];
}
